            forecast: -{
                forecastday: -[
                   -{
                        astro: -{
                            moon_illumination: "99",
                            moon_phase: "Waxing Gibbous",
                            moonrise: "10:16 PM",
                            moonset: "04:17 AM",
                            sunrise: "05:30 AM",
                            sunset: "09:44 PM"
                        },
                        date: "2022-07-13",
                        date_epoch: 1657670400,
                        day: -{
                            avghumidity: 45,
                            avgtemp_c: 24.4,
                            avgtemp_f: 75.9,
                            avgvis_km: 10,
                            avgvis_miles: 6,
                            condition: +{3 items},
                            daily_chance_of_rain: 0,
                            daily_chance_of_snow: 0,
                            daily_will_it_rain: 0,
                            daily_will_it_snow: 0,
                            maxtemp_c: 30.6,
                            maxtemp_f: 87.1,
                            maxwind_kph: 20.2,
                            maxwind_mph: 12.5,
                            mintemp_c: 20,
                            mintemp_f: 68,
                            totalprecip_in: 0,
                            totalprecip_mm: 0,
                            uv: 6
                        },
                        hour: -[{ 'time_epoch': 1657663200, 'time': '2022-07-13 00:00', 'temp_c': 21.2, 'temp_f': 70.2, 'is_day': 0, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/night/116.png', 'code': 1003 }, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 162, 'wind_dir': 'SSE', 'pressure_mb': 1022.0, 'pressure_in': 30.19, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 47, 'cloud': 32, 'feelslike_c': 21.2, 'feelslike_f': 70.2, 'windchill_c': 21.2, 'windchill_f': 70.2, 'heatindex_c': 24.2, 'heatindex_f': 75.6, 'dewpoint_c': 9.4, 'dewpoint_f': 48.9, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 8.9, 'gust_kph': 14.4, 'uv': 1.0 },
                            { 'time_epoch': 1657666800, 'time': '2022-07-13 01:00', 'temp_c': 21.2, 'temp_f': 70.2, 'is_day': 0, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/night/116.png', 'code': 1003 }, 'wind_mph': 3.4, 'wind_kph': 5.4, 'wind_degree': 180, 'wind_dir': 'S', 'pressure_mb': 1022.0, 'pressure_in': 30.18, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 47, 'cloud': 46, 'feelslike_c': 21.2, 'feelslike_f': 70.2, 'windchill_c': 21.2, 'windchill_f': 70.2, 'heatindex_c': 24.2, 'heatindex_f': 75.6, 'dewpoint_c': 9.3, 'dewpoint_f': 48.7, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 6.9, 'gust_kph': 11.2, 'uv': 1.0 },
                            { 'time_epoch': 1657670400, 'time': '2022-07-13 02:00', 'temp_c': 21.2, 'temp_f': 70.2, 'is_day': 0, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/night/116.png', 'code': 1003 }, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 169, 'wind_dir': 'S', 'pressure_mb': 1022.0, 'pressure_in': 30.17, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 47, 'cloud': 46, 'feelslike_c': 21.2, 'feelslike_f': 70.2, 'windchill_c': 21.2, 'windchill_f': 70.2, 'heatindex_c': 24.2, 'heatindex_f': 75.6, 'dewpoint_c': 9.4, 'dewpoint_f': 48.9, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 8.7, 'gust_kph': 14.0, 'uv': 1.0 },
                            { 'time_epoch': 1657674000, 'time': '2022-07-13 03:00', 'temp_c': 21.0, 'temp_f': 69.8, 'is_day': 0, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/night/116.png', 'code': 1003 }, 'wind_mph': 5.4, 'wind_kph': 8.6, 'wind_degree': 168, 'wind_dir': 'SSE', 'pressure_mb': 1021.0, 'pressure_in': 30.14, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 48, 'cloud': 28, 'feelslike_c': 21.0, 'feelslike_f': 69.8, 'windchill_c': 21.0, 'windchill_f': 69.8, 'heatindex_c': 21.0, 'heatindex_f': 69.8, 'dewpoint_c': 9.6, 'dewpoint_f': 49.3, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.2, 'gust_kph': 18.0, 'uv': 1.0 },
                            { 'time_epoch': 1657677600, 'time': '2022-07-13 04:00', 'temp_c': 21.3, 'temp_f': 70.3, 'is_day': 0, 'condition': { 'text': 'Clear', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000 }, 'wind_mph': 5.1, 'wind_kph': 8.3, 'wind_degree': 177, 'wind_dir': 'S', 'pressure_mb': 1020.0, 'pressure_in': 30.12, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 49, 'cloud': 13, 'feelslike_c': 21.3, 'feelslike_f': 70.3, 'windchill_c': 21.3, 'windchill_f': 70.3, 'heatindex_c': 24.3, 'heatindex_f': 75.7, 'dewpoint_c': 10.1, 'dewpoint_f': 50.2, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 10.7, 'gust_kph': 17.3, 'uv': 1.0 },
                            { 'time_epoch': 1657681200, 'time': '2022-07-13 05:00', 'temp_c': 21.2, 'temp_f': 70.2, 'is_day': 0, 'condition': { 'text': 'Clear', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000 }, 'wind_mph': 5.1, 'wind_kph': 8.3, 'wind_degree': 194, 'wind_dir': 'SSW', 'pressure_mb': 1020.0, 'pressure_in': 30.12, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 50, 'cloud': 12, 'feelslike_c': 21.2, 'feelslike_f': 70.2, 'windchill_c': 21.2, 'windchill_f': 70.2, 'heatindex_c': 24.3, 'heatindex_f': 75.7, 'dewpoint_c': 10.5, 'dewpoint_f': 50.9, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 10.7, 'gust_kph': 17.3, 'uv': 1.0 },
                            { 'time_epoch': 1657684800, 'time': '2022-07-13 06:00', 'temp_c': 21.2, 'temp_f': 70.2, 'is_day': 1, 'condition': { 'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000 }, 'wind_mph': 5.8, 'wind_kph': 9.4, 'wind_degree': 203, 'wind_dir': 'SSW', 'pressure_mb': 1020.0, 'pressure_in': 30.12, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 52, 'cloud': 17, 'feelslike_c': 21.2, 'feelslike_f': 70.2, 'windchill_c': 21.2, 'windchill_f': 70.2, 'heatindex_c': 24.4, 'heatindex_f': 75.9, 'dewpoint_c': 11.0, 'dewpoint_f': 51.8, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.6, 'gust_kph': 18.7, 'uv': 6.0 },
                            { 'time_epoch': 1657688400, 'time': '2022-07-13 07:00', 'temp_c': 22.7, 'temp_f': 72.9, 'is_day': 1, 'condition': { 'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000 }, 'wind_mph': 6.5, 'wind_kph': 10.4, 'wind_degree': 208, 'wind_dir': 'SSW', 'pressure_mb': 1020.0, 'pressure_in': 30.13, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 50, 'cloud': 12, 'feelslike_c': 24.6, 'feelslike_f': 76.3, 'windchill_c': 22.7, 'windchill_f': 72.9, 'heatindex_c': 24.6, 'heatindex_f': 76.3, 'dewpoint_c': 11.9, 'dewpoint_f': 53.4, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 10.1, 'gust_kph': 16.2, 'uv': 6.0 },
                            { 'time_epoch': 1657692000, 'time': '2022-07-13 08:00', 'temp_c': 23.2, 'temp_f': 73.8, 'is_day': 1, 'condition': { 'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000 }, 'wind_mph': 7.6, 'wind_kph': 12.2, 'wind_degree': 217, 'wind_dir': 'SW', 'pressure_mb': 1020.0, 'pressure_in': 30.13, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 48, 'cloud': 8, 'feelslike_c': 24.8, 'feelslike_f': 76.6, 'windchill_c': 23.2, 'windchill_f': 73.8, 'heatindex_c': 24.8, 'heatindex_f': 76.6, 'dewpoint_c': 11.7, 'dewpoint_f': 53.1, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.2, 'gust_kph': 18.0, 'uv': 6.0 },
                            { 'time_epoch': 1657695600, 'time': '2022-07-13 09:00', 'temp_c': 25.1, 'temp_f': 77.2, 'is_day': 1, 'condition': { 'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000 }, 'wind_mph': 9.6, 'wind_kph': 15.5, 'wind_degree': 239, 'wind_dir': 'WSW', 'pressure_mb': 1020.0, 'pressure_in': 30.12, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 40, 'cloud': 9, 'feelslike_c': 25.4, 'feelslike_f': 77.7, 'windchill_c': 25.1, 'windchill_f': 77.2, 'heatindex_c': 25.4, 'heatindex_f': 77.7, 'dewpoint_c': 10.6, 'dewpoint_f': 51.1, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.9, 'gust_kph': 19.1, 'uv': 7.0 },
                            { 'time_epoch': 1657699200, 'time': '2022-07-13 10:00', 'temp_c': 27.1, 'temp_f': 80.8, 'is_day': 1, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003 }, 'wind_mph': 12.5, 'wind_kph': 20.2, 'wind_degree': 249, 'wind_dir': 'WSW', 'pressure_mb': 1020.0, 'pressure_in': 30.11, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 35, 'cloud': 45, 'feelslike_c': 26.6, 'feelslike_f': 79.9, 'windchill_c': 27.1, 'windchill_f': 80.8, 'heatindex_c': 26.6, 'heatindex_f': 79.9, 'dewpoint_c': 10.4, 'dewpoint_f': 50.7, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 14.3, 'gust_kph': 23.0, 'uv': 7.0 },
                            { 'time_epoch': 1657702800, 'time': '2022-07-13 11:00', 'temp_c': 26.4, 'temp_f': 79.5, 'is_day': 1, 'condition': { 'text': 'Cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/day/119.png', 'code': 1006 }, 'wind_mph': 9.8, 'wind_kph': 15.8, 'wind_degree': 243, 'wind_dir': 'WSW', 'pressure_mb': 1020.0, 'pressure_in': 30.11, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 38, 'cloud': 75, 'feelslike_c': 26.2, 'feelslike_f': 79.2, 'windchill_c': 26.4, 'windchill_f': 79.5, 'heatindex_c': 26.2, 'heatindex_f': 79.2, 'dewpoint_c': 11.0, 'dewpoint_f': 51.8, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.4, 'gust_kph': 18.4, 'uv': 6.0 },
                            { 'time_epoch': 1657706400, 'time': '2022-07-13 12:00', 'temp_c': 26.0, 'temp_f': 78.8, 'is_day': 1, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003 }, 'wind_mph': 9.6, 'wind_kph': 15.5, 'wind_degree': 240, 'wind_dir': 'WSW', 'pressure_mb': 1020.0, 'pressure_in': 30.11, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 40, 'cloud': 49, 'feelslike_c': 26.0, 'feelslike_f': 78.8, 'windchill_c': 26.0, 'windchill_f': 78.8, 'heatindex_c': 26.0, 'heatindex_f': 78.8, 'dewpoint_c': 11.2, 'dewpoint_f': 52.2, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.2, 'gust_kph': 18.0, 'uv': 7.0 },
                            { 'time_epoch': 1657710000, 'time': '2022-07-13 13:00', 'temp_c': 27.7, 'temp_f': 81.9, 'is_day': 1, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003 }, 'wind_mph': 8.3, 'wind_kph': 13.3, 'wind_degree': 265, 'wind_dir': 'W', 'pressure_mb': 1019.0, 'pressure_in': 30.1, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 34, 'cloud': 54, 'feelslike_c': 27.1, 'feelslike_f': 80.8, 'windchill_c': 27.7, 'windchill_f': 81.9, 'heatindex_c': 27.1, 'heatindex_f': 80.8, 'dewpoint_c': 10.5, 'dewpoint_f': 50.9, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 9.6, 'gust_kph': 15.5, 'uv': 7.0 },
                            { 'time_epoch': 1657713600, 'time': '2022-07-13 14:00', 'temp_c': 29.6, 'temp_f': 85.3, 'is_day': 1, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003 }, 'wind_mph': 8.5, 'wind_kph': 13.7, 'wind_degree': 290, 'wind_dir': 'WNW', 'pressure_mb': 1019.0, 'pressure_in': 30.08, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 32, 'cloud': 31, 'feelslike_c': 28.7, 'feelslike_f': 83.7, 'windchill_c': 29.6, 'windchill_f': 85.3, 'heatindex_c': 28.7, 'heatindex_f': 83.7, 'dewpoint_c': 11.3, 'dewpoint_f': 52.3, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 9.8, 'gust_kph': 15.8, 'uv': 7.0 },
                            { 'time_epoch': 1657717200, 'time': '2022-07-13 15:00', 'temp_c': 30.6, 'temp_f': 87.1, 'is_day': 1, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003 }, 'wind_mph': 11.0, 'wind_kph': 17.6, 'wind_degree': 298, 'wind_dir': 'WNW', 'pressure_mb': 1018.0, 'pressure_in': 30.06, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 32, 'cloud': 33, 'feelslike_c': 29.9, 'feelslike_f': 85.8, 'windchill_c': 30.6, 'windchill_f': 87.1, 'heatindex_c': 29.9, 'heatindex_f': 85.8, 'dewpoint_c': 12.3, 'dewpoint_f': 54.1, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 12.5, 'gust_kph': 20.2, 'uv': 8.0 },
                            { 'time_epoch': 1657720800, 'time': '2022-07-13 16:00', 'temp_c': 29.7, 'temp_f': 85.5, 'is_day': 1, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003 }, 'wind_mph': 12.1, 'wind_kph': 19.4, 'wind_degree': 310, 'wind_dir': 'NW', 'pressure_mb': 1018.0, 'pressure_in': 30.06, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 34, 'cloud': 47, 'feelslike_c': 29.1, 'feelslike_f': 84.4, 'windchill_c': 29.7, 'windchill_f': 85.5, 'heatindex_c': 29.1, 'heatindex_f': 84.4, 'dewpoint_c': 12.3, 'dewpoint_f': 54.1, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 13.9, 'gust_kph': 22.3, 'uv': 7.0 },
                            { 'time_epoch': 1657724400, 'time': '2022-07-13 17:00', 'temp_c': 27.9, 'temp_f': 82.2, 'is_day': 1, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003 }, 'wind_mph': 9.6, 'wind_kph': 15.5, 'wind_degree': 318, 'wind_dir': 'NW', 'pressure_mb': 1018.0, 'pressure_in': 30.06, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 37, 'cloud': 45, 'feelslike_c': 27.5, 'feelslike_f': 81.5, 'windchill_c': 27.9, 'windchill_f': 82.2, 'heatindex_c': 27.5, 'heatindex_f': 81.5, 'dewpoint_c': 12.1, 'dewpoint_f': 53.8, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.4, 'gust_kph': 18.4, 'uv': 7.0 },
                            { 'time_epoch': 1657728000, 'time': '2022-07-13 18:00', 'temp_c': 26.9, 'temp_f': 80.4, 'is_day': 1, 'condition': { 'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000 }, 'wind_mph': 7.6, 'wind_kph': 12.2, 'wind_degree': 305, 'wind_dir': 'NW', 'pressure_mb': 1018.0, 'pressure_in': 30.06, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 40, 'cloud': 17, 'feelslike_c': 26.8, 'feelslike_f': 80.2, 'windchill_c': 26.9, 'windchill_f': 80.4, 'heatindex_c': 26.8, 'heatindex_f': 80.2, 'dewpoint_c': 12.1, 'dewpoint_f': 53.8, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 10.3, 'gust_kph': 16.6, 'uv': 7.0 },
                            { 'time_epoch': 1657731600, 'time': '2022-07-13 19:00', 'temp_c': 26.0, 'temp_f': 78.8, 'is_day': 1, 'condition': { 'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000 }, 'wind_mph': 6.5, 'wind_kph': 10.4, 'wind_degree': 303, 'wind_dir': 'WNW', 'pressure_mb': 1018.0, 'pressure_in': 30.06, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 43, 'cloud': 17, 'feelslike_c': 26.2, 'feelslike_f': 79.2, 'windchill_c': 26.0, 'windchill_f': 78.8, 'heatindex_c': 26.2, 'heatindex_f': 79.2, 'dewpoint_c': 12.4, 'dewpoint_f': 54.3, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 9.6, 'gust_kph': 15.5, 'uv': 7.0 },
                            { 'time_epoch': 1657735200, 'time': '2022-07-13 20:00', 'temp_c': 24.6, 'temp_f': 76.3, 'is_day': 1, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003 }, 'wind_mph': 8.7, 'wind_kph': 14.0, 'wind_degree': 346, 'wind_dir': 'NNW', 'pressure_mb': 1019.0, 'pressure_in': 30.09, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 47, 'cloud': 26, 'feelslike_c': 25.4, 'feelslike_f': 77.7, 'windchill_c': 24.6, 'windchill_f': 76.3, 'heatindex_c': 25.4, 'heatindex_f': 77.7, 'dewpoint_c': 12.5, 'dewpoint_f': 54.5, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 12.5, 'gust_kph': 20.2, 'uv': 6.0 },
                            { 'time_epoch': 1657738800, 'time': '2022-07-13 21:00', 'temp_c': 22.6, 'temp_f': 72.7, 'is_day': 1, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003 }, 'wind_mph': 8.3, 'wind_kph': 13.3, 'wind_degree': 2, 'wind_dir': 'N', 'pressure_mb': 1020.0, 'pressure_in': 30.11, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 56, 'cloud': 46, 'feelslike_c': 24.7, 'feelslike_f': 76.5, 'windchill_c': 22.6, 'windchill_f': 72.7, 'heatindex_c': 24.7, 'heatindex_f': 76.5, 'dewpoint_c': 13.3, 'dewpoint_f': 55.9, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.0, 'gust_kph': 17.6, 'uv': 6.0 },
                            { 'time_epoch': 1657742400, 'time': '2022-07-13 22:00', 'temp_c': 21.0, 'temp_f': 69.8, 'is_day': 0, 'condition': { 'text': 'Cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/night/119.png', 'code': 1006 }, 'wind_mph': 6.7, 'wind_kph': 10.8, 'wind_degree': 16, 'wind_dir': 'NNE', 'pressure_mb': 1020.0, 'pressure_in': 30.12, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 63, 'cloud': 77, 'feelslike_c': 21.0, 'feelslike_f': 69.8, 'windchill_c': 21.0, 'windchill_f': 69.8, 'heatindex_c': 21.0, 'heatindex_f': 69.8, 'dewpoint_c': 13.8, 'dewpoint_f': 56.8, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 8.9, 'gust_kph': 14.4, 'uv': 1.0 },
                            { 'time_epoch': 1657746000, 'time': '2022-07-13 23:00', 'temp_c': 20.0, 'temp_f': 68.0, 'is_day': 0, 'condition': { 'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/night/116.png', 'code': 1003 }, 'wind_mph': 6.5, 'wind_kph': 10.4, 'wind_degree': 24, 'wind_dir': 'NNE', 'pressure_mb': 1020.0, 'pressure_in': 30.12, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 66, 'cloud': 46, 'feelslike_c': 20.0, 'feelslike_f': 68.0, 'windchill_c': 20.0, 'windchill_f': 68.0, 'heatindex_c': 20.0, 'heatindex_f': 68.0, 'dewpoint_c': 13.4, 'dewpoint_f': 56.1, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 8.9, 'gust_kph': 14.4, 'uv': 1.0 }]
                    },
                   -{
                        astro: -{
                            moon_illumination: "100",
                            moon_phase: "Full Moon",
                            moonrise: "10:58 PM",
                            moonset: "05:37 AM",
                            sunrise: "05:31 AM",
                            sunset: "09:43 PM"
                        },
                        date: "2022-07-14",
                        date_epoch: 1657756800,
                        day: -{
                            avghumidity: 50,
                            avgtemp_c: 20.1,
                            avgtemp_f: 68.2,
                            avgvis_km: 10,
                            avgvis_miles: 6,
                            condition: -{
                                code: 1000,
                                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                text: "Sunny"
                            },
                            daily_chance_of_rain: 0,
                            daily_chance_of_snow: 0,
                            daily_will_it_rain: 0,
                            daily_will_it_snow: 0,
                            maxtemp_c: 26,
                            maxtemp_f: 78.8,
                            maxwind_kph: 19.4,
                            maxwind_mph: 12.1,
                            mintemp_c: 15.2,
                            mintemp_f: 59.4,
                            totalprecip_in: 0,
                            totalprecip_mm: 0,
                            uv: 6
                        },
                        hour: -[
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 46,
                                condition: +{3 items},
                                dewpoint_c: 12.8,
                                dewpoint_f: 55,
                                feelslike_c: 19.2,
                                feelslike_f: 66.6,
                                gust_kph: 13.3,
                                gust_mph: 8.3,
                                heatindex_c: 19.2,
                                heatindex_f: 66.6,
                                humidity: 66,
                                is_day: 0,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.12,
                                pressure_mb: 1020,
                                temp_c: 19.2,
                                temp_f: 66.6,
                                time: "2022-07-14 00:00",
                                time_epoch: 1657749600,
                                uv: 1,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 26,
                                wind_dir: "NNE",
                                wind_kph: 9.7,
                                wind_mph: 6,
                                windchill_c: 19.2,
                                windchill_f: 66.6
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 28,
                                condition: +{3 items},
                                dewpoint_c: 12,
                                dewpoint_f: 53.6,
                                feelslike_c: 18.3,
                                feelslike_f: 64.9,
                                gust_kph: 11.5,
                                gust_mph: 7.2,
                                heatindex_c: 18.3,
                                heatindex_f: 64.9,
                                humidity: 67,
                                is_day: 0,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.12,
                                pressure_mb: 1020,
                                temp_c: 18.3,
                                temp_f: 64.9,
                                time: "2022-07-14 01:00",
                                time_epoch: 1657753200,
                                uv: 1,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 20,
                                wind_dir: "NNE",
                                wind_kph: 8.3,
                                wind_mph: 5.1,
                                windchill_c: 18.3,
                                windchill_f: 64.9
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 38,
                                condition: +{3 items},
                                dewpoint_c: 11.5,
                                dewpoint_f: 52.7,
                                feelslike_c: 17.5,
                                feelslike_f: 63.5,
                                gust_kph: 13,
                                gust_mph: 8.1,
                                heatindex_c: 17.5,
                                heatindex_f: 63.5,
                                humidity: 68,
                                is_day: 0,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.1,
                                pressure_mb: 1019,
                                temp_c: 17.5,
                                temp_f: 63.5,
                                time: "2022-07-14 02:00",
                                time_epoch: 1657756800,
                                uv: 1,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 23,
                                wind_dir: "NNE",
                                wind_kph: 9,
                                wind_mph: 5.6,
                                windchill_c: 17.5,
                                windchill_f: 63.5
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 21,
                                condition: +{3 items},
                                dewpoint_c: 11.2,
                                dewpoint_f: 52.2,
                                feelslike_c: 17.3,
                                feelslike_f: 63.1,
                                gust_kph: 10.4,
                                gust_mph: 6.5,
                                heatindex_c: 17.3,
                                heatindex_f: 63.1,
                                humidity: 68,
                                is_day: 0,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.11,
                                pressure_mb: 1020,
                                temp_c: 17.3,
                                temp_f: 63.1,
                                time: "2022-07-14 03:00",
                                time_epoch: 1657760400,
                                uv: 1,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 32,
                                wind_dir: "NNE",
                                wind_kph: 7.6,
                                wind_mph: 4.7,
                                windchill_c: 17.3,
                                windchill_f: 63.1
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 34,
                                condition: +{3 items},
                                dewpoint_c: 11,
                                dewpoint_f: 51.8,
                                feelslike_c: 16.8,
                                feelslike_f: 62.2,
                                gust_kph: 9.7,
                                gust_mph: 6,
                                heatindex_c: 16.8,
                                heatindex_f: 62.2,
                                humidity: 68,
                                is_day: 0,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.11,
                                pressure_mb: 1020,
                                temp_c: 16.8,
                                temp_f: 62.2,
                                time: "2022-07-14 04:00",
                                time_epoch: 1657764000,
                                uv: 1,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 11,
                                wind_dir: "NNE",
                                wind_kph: 7.2,
                                wind_mph: 4.5,
                                windchill_c: 16.8,
                                windchill_f: 62.2
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 30,
                                condition: +{3 items},
                                dewpoint_c: 10.7,
                                dewpoint_f: 51.3,
                                feelslike_c: 16.4,
                                feelslike_f: 61.5,
                                gust_kph: 10.1,
                                gust_mph: 6.3,
                                heatindex_c: 16.4,
                                heatindex_f: 61.5,
                                humidity: 69,
                                is_day: 0,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.1,
                                pressure_mb: 1019,
                                temp_c: 16.4,
                                temp_f: 61.5,
                                time: "2022-07-14 05:00",
                                time_epoch: 1657767600,
                                uv: 1,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 25,
                                wind_dir: "NNE",
                                wind_kph: 7.6,
                                wind_mph: 4.7,
                                windchill_c: 16.4,
                                windchill_f: 61.5
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 22,
                                condition: +{3 items},
                                dewpoint_c: 10.4,
                                dewpoint_f: 50.7,
                                feelslike_c: 16.2,
                                feelslike_f: 61.2,
                                gust_kph: 11.2,
                                gust_mph: 6.9,
                                heatindex_c: 16.2,
                                heatindex_f: 61.2,
                                humidity: 69,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.1,
                                pressure_mb: 1019,
                                temp_c: 16.2,
                                temp_f: 61.2,
                                time: "2022-07-14 06:00",
                                time_epoch: 1657771200,
                                uv: 5,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 25,
                                wind_dir: "NNE",
                                wind_kph: 8.6,
                                wind_mph: 5.4,
                                windchill_c: 16.2,
                                windchill_f: 61.2
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 24,
                                condition: +{3 items},
                                dewpoint_c: 9.8,
                                dewpoint_f: 49.6,
                                feelslike_c: 16.7,
                                feelslike_f: 62.1,
                                gust_kph: 11.2,
                                gust_mph: 6.9,
                                heatindex_c: 16.7,
                                heatindex_f: 62.1,
                                humidity: 64,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.1,
                                pressure_mb: 1019,
                                temp_c: 16.7,
                                temp_f: 62.1,
                                time: "2022-07-14 07:00",
                                time_epoch: 1657774800,
                                uv: 5,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 30,
                                wind_dir: "NNE",
                                wind_kph: 9,
                                wind_mph: 5.6,
                                windchill_c: 16.7,
                                windchill_f: 62.1
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 26,
                                condition: +{3 items},
                                dewpoint_c: 8.9,
                                dewpoint_f: 48,
                                feelslike_c: 17.5,
                                feelslike_f: 63.5,
                                gust_kph: 8.6,
                                gust_mph: 5.4,
                                heatindex_c: 17.5,
                                heatindex_f: 63.5,
                                humidity: 57,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.1,
                                pressure_mb: 1019,
                                temp_c: 17.5,
                                temp_f: 63.5,
                                time: "2022-07-14 08:00",
                                time_epoch: 1657778400,
                                uv: 5,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 27,
                                wind_dir: "NNE",
                                wind_kph: 7.2,
                                wind_mph: 4.5,
                                windchill_c: 17.5,
                                windchill_f: 63.5
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 27,
                                condition: +{3 items},
                                dewpoint_c: 7.5,
                                dewpoint_f: 45.5,
                                feelslike_c: 18.3,
                                feelslike_f: 64.9,
                                gust_kph: 7.6,
                                gust_mph: 4.7,
                                heatindex_c: 18.3,
                                heatindex_f: 64.9,
                                humidity: 49,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.09,
                                pressure_mb: 1019,
                                temp_c: 18.3,
                                temp_f: 64.9,
                                time: "2022-07-14 09:00",
                                time_epoch: 1657782000,
                                uv: 5,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 29,
                                wind_dir: "NNE",
                                wind_kph: 6.1,
                                wind_mph: 3.8,
                                windchill_c: 18.3,
                                windchill_f: 64.9
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 25,
                                condition: +{3 items},
                                dewpoint_c: 6.1,
                                dewpoint_f: 43,
                                feelslike_c: 19.9,
                                feelslike_f: 67.8,
                                gust_kph: 5,
                                gust_mph: 3.1,
                                heatindex_c: 19.9,
                                heatindex_f: 67.8,
                                humidity: 40,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.09,
                                pressure_mb: 1019,
                                temp_c: 19.9,
                                temp_f: 67.8,
                                time: "2022-07-14 10:00",
                                time_epoch: 1657785600,
                                uv: 5,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 19,
                                wind_dir: "NNE",
                                wind_kph: 4.3,
                                wind_mph: 2.7,
                                windchill_c: 19.9,
                                windchill_f: 67.8
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 23,
                                condition: +{3 items},
                                dewpoint_c: 5.8,
                                dewpoint_f: 42.4,
                                feelslike_c: 23.8,
                                feelslike_f: 74.8,
                                gust_kph: 5.8,
                                gust_mph: 3.6,
                                heatindex_c: 23.8,
                                heatindex_f: 74.8,
                                humidity: 34,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.07,
                                pressure_mb: 1018,
                                temp_c: 22.5,
                                temp_f: 72.5,
                                time: "2022-07-14 11:00",
                                time_epoch: 1657789200,
                                uv: 6,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 343,
                                wind_dir: "NNW",
                                wind_kph: 5,
                                wind_mph: 3.1,
                                windchill_c: 22.5,
                                windchill_f: 72.5
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 23,
                                condition: +{3 items},
                                dewpoint_c: 5.5,
                                dewpoint_f: 41.9,
                                feelslike_c: 23.9,
                                feelslike_f: 75,
                                gust_kph: 8.3,
                                gust_mph: 5.1,
                                heatindex_c: 23.9,
                                heatindex_f: 75,
                                humidity: 32,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.06,
                                pressure_mb: 1018,
                                temp_c: 23.1,
                                temp_f: 73.6,
                                time: "2022-07-14 12:00",
                                time_epoch: 1657792800,
                                uv: 6,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 323,
                                wind_dir: "NW",
                                wind_kph: 7.2,
                                wind_mph: 4.5,
                                windchill_c: 23.1,
                                windchill_f: 73.6
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 24,
                                condition: +{3 items},
                                dewpoint_c: 5.8,
                                dewpoint_f: 42.4,
                                feelslike_c: 24.3,
                                feelslike_f: 75.7,
                                gust_kph: 11.9,
                                gust_mph: 7.4,
                                heatindex_c: 24.3,
                                heatindex_f: 75.7,
                                humidity: 30,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.05,
                                pressure_mb: 1018,
                                temp_c: 24.3,
                                temp_f: 75.7,
                                time: "2022-07-14 13:00",
                                time_epoch: 1657796400,
                                uv: 6,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 325,
                                wind_dir: "NW",
                                wind_kph: 10.4,
                                wind_mph: 6.5,
                                windchill_c: 24.3,
                                windchill_f: 75.7
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 24,
                                condition: +{3 items},
                                dewpoint_c: 6.8,
                                dewpoint_f: 44.2,
                                feelslike_c: 25.1,
                                feelslike_f: 77.2,
                                gust_kph: 16.9,
                                gust_mph: 10.5,
                                heatindex_c: 25.1,
                                heatindex_f: 77.2,
                                humidity: 30,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.05,
                                pressure_mb: 1018,
                                temp_c: 25.6,
                                temp_f: 78.1,
                                time: "2022-07-14 14:00",
                                time_epoch: 1657800000,
                                uv: 7,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 324,
                                wind_dir: "NW",
                                wind_kph: 14.8,
                                wind_mph: 9.2,
                                windchill_c: 25.6,
                                windchill_f: 78.1
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 21,
                                condition: +{3 items},
                                dewpoint_c: 7.1,
                                dewpoint_f: 44.8,
                                feelslike_c: 25.4,
                                feelslike_f: 77.7,
                                gust_kph: 17.3,
                                gust_mph: 10.7,
                                heatindex_c: 25.4,
                                heatindex_f: 77.7,
                                humidity: 30,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.05,
                                pressure_mb: 1018,
                                temp_c: 26,
                                temp_f: 78.8,
                                time: "2022-07-14 15:00",
                                time_epoch: 1657803600,
                                uv: 7,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 316,
                                wind_dir: "NW",
                                wind_kph: 15.1,
                                wind_mph: 9.4,
                                windchill_c: 26,
                                windchill_f: 78.8
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 21,
                                condition: +{3 items},
                                dewpoint_c: 7.6,
                                dewpoint_f: 45.7,
                                feelslike_c: 25.3,
                                feelslike_f: 77.5,
                                gust_kph: 21.6,
                                gust_mph: 13.4,
                                heatindex_c: 25.3,
                                heatindex_f: 77.5,
                                humidity: 31,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.05,
                                pressure_mb: 1018,
                                temp_c: 25.8,
                                temp_f: 78.4,
                                time: "2022-07-14 16:00",
                                time_epoch: 1657807200,
                                uv: 7,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 327,
                                wind_dir: "NNW",
                                wind_kph: 18.7,
                                wind_mph: 11.6,
                                windchill_c: 25.8,
                                windchill_f: 78.4
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 26,
                                condition: +{3 items},
                                dewpoint_c: 7.5,
                                dewpoint_f: 45.5,
                                feelslike_c: 24.8,
                                feelslike_f: 76.6,
                                gust_kph: 22.3,
                                gust_mph: 13.9,
                                heatindex_c: 24.8,
                                heatindex_f: 76.6,
                                humidity: 33,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.05,
                                pressure_mb: 1018,
                                temp_c: 24.8,
                                temp_f: 76.6,
                                time: "2022-07-14 17:00",
                                time_epoch: 1657810800,
                                uv: 6,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 320,
                                wind_dir: "NW",
                                wind_kph: 19.4,
                                wind_mph: 12.1,
                                windchill_c: 24.8,
                                windchill_f: 76.6
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 21,
                                condition: +{3 items},
                                dewpoint_c: 7.7,
                                dewpoint_f: 45.9,
                                feelslike_c: 24.6,
                                feelslike_f: 76.3,
                                gust_kph: 22,
                                gust_mph: 13.6,
                                heatindex_c: 24.6,
                                heatindex_f: 76.3,
                                humidity: 35,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.06,
                                pressure_mb: 1018,
                                temp_c: 24.2,
                                temp_f: 75.6,
                                time: "2022-07-14 18:00",
                                time_epoch: 1657814400,
                                uv: 6,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 318,
                                wind_dir: "NW",
                                wind_kph: 19.1,
                                wind_mph: 11.9,
                                windchill_c: 24.2,
                                windchill_f: 75.6
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 25,
                                condition: +{3 items},
                                dewpoint_c: 8.6,
                                dewpoint_f: 47.5,
                                feelslike_c: 24.3,
                                feelslike_f: 75.7,
                                gust_kph: 21.6,
                                gust_mph: 13.4,
                                heatindex_c: 24.3,
                                heatindex_f: 75.7,
                                humidity: 40,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.08,
                                pressure_mb: 1019,
                                temp_c: 22.8,
                                temp_f: 73,
                                time: "2022-07-14 19:00",
                                time_epoch: 1657818000,
                                uv: 6,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 327,
                                wind_dir: "NNW",
                                wind_kph: 18.7,
                                wind_mph: 11.6,
                                windchill_c: 22.8,
                                windchill_f: 73
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 21,
                                condition: +{3 items},
                                dewpoint_c: 8.1,
                                dewpoint_f: 46.6,
                                feelslike_c: 19.9,
                                feelslike_f: 67.8,
                                gust_kph: 23.8,
                                gust_mph: 14.8,
                                heatindex_c: 19.9,
                                heatindex_f: 67.8,
                                humidity: 47,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.11,
                                pressure_mb: 1020,
                                temp_c: 19.9,
                                temp_f: 67.8,
                                time: "2022-07-14 20:00",
                                time_epoch: 1657821600,
                                uv: 5,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 326,
                                wind_dir: "NNW",
                                wind_kph: 18,
                                wind_mph: 11.2,
                                windchill_c: 19.9,
                                windchill_f: 67.8
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 7,
                                condition: +{3 items},
                                dewpoint_c: 8.4,
                                dewpoint_f: 47.1,
                                feelslike_c: 18,
                                feelslike_f: 64.4,
                                gust_kph: 20.9,
                                gust_mph: 13,
                                heatindex_c: 18,
                                heatindex_f: 64.4,
                                humidity: 53,
                                is_day: 1,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.13,
                                pressure_mb: 1020,
                                temp_c: 18,
                                temp_f: 64.4,
                                time: "2022-07-14 21:00",
                                time_epoch: 1657825200,
                                uv: 5,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 328,
                                wind_dir: "NNW",
                                wind_kph: 15.5,
                                wind_mph: 9.6,
                                windchill_c: 18,
                                windchill_f: 64.4
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 6,
                                condition: +{3 items},
                                dewpoint_c: 8.6,
                                dewpoint_f: 47.5,
                                feelslike_c: 16.7,
                                feelslike_f: 62.1,
                                gust_kph: 18.4,
                                gust_mph: 11.4,
                                heatindex_c: 16.7,
                                heatindex_f: 62.1,
                                humidity: 59,
                                is_day: 0,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.15,
                                pressure_mb: 1021,
                                temp_c: 16.7,
                                temp_f: 62.1,
                                time: "2022-07-14 22:00",
                                time_epoch: 1657828800,
                                uv: 1,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 326,
                                wind_dir: "NNW",
                                wind_kph: 13.7,
                                wind_mph: 8.5,
                                windchill_c: 16.7,
                                windchill_f: 62.1
                            },
                           -{
                                chance_of_rain: 0,
                                chance_of_snow: 0,
                                cloud: 6,
                                condition: +{3 items},
                                dewpoint_c: 8.4,
                                dewpoint_f: 47.1,
                                feelslike_c: 15.2,
                                feelslike_f: 59.4,
                                gust_kph: 15.8,
                                gust_mph: 9.8,
                                heatindex_c: 15.2,
                                heatindex_f: 59.4,
                                humidity: 64,
                                is_day: 0,
                                precip_in: 0,
                                precip_mm: 0,
                                pressure_in: 30.17,
                                pressure_mb: 1022,
                                temp_c: 15.2,
                                temp_f: 59.4,
                                time: "2022-07-14 23:00",
                                time_epoch: 1657832400,
                                uv: 1,
                                vis_km: 10,
                                vis_miles: 6,
                                will_it_rain: 0,
                                will_it_snow: 0,
                                wind_degree: 325,
                                wind_dir: "NW",
                                wind_kph: 10.8,
                                wind_mph: 6.7,
                                windchill_c: 15.2,
                                windchill_f: 59.4
                            }
                        ]
                    }
                ]
            },
            location: -{
                country: "Germany",
                lat: 51.4,
                localtime: "2022-07-13 19:29",
                localtime_epoch: 1657733362,
                lon: 7.17,
                name: "Hattingen",
                region: "Nordrhein-Westfalen",
                tz_id: "Europe/Berlin"
            }
        },